### ISSUE TITLE
Add Swagger

### ISSUE THREAD

**Issue by AliMol** [danielfsousa/express-rest-boilerplate#122]
Any refrence on how to enable swagger documentation on the express routes ?

**Comment by danielfsousa** [comment]
I haven't included swagger in this boilerplate, but you can take a look at the [swagger-node docs](https://github.com/swagger-api/swagger-node/blob/master/docs/README.md)

**Comment by marcoswca** [comment]
@danielfsousa Would you consider a contribution to include swagger documentation?

**Comment by danielfsousa** [comment]
> @danielfsousa Would you consider a contribution to include swagger documentation?

Yes! That would be great.

**Comment by danielfsousa** [comment]
Opening for [hacktoberfest](https://hacktoberfest.digitalocean.com/).
