### ISSUE TITLE
calling new RefreshToken from within the model gives problems

### ISSUE THREAD

**Issue by gkatsanos** [danielfsousa/express-rest-boilerplate#125]
https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/032a005deaa68a06f476432f4d602917609a251a/src/api/models/refreshToken.model.js#L41

Hey Daniel, how's it going? 
I was cleaning up my API based on your boilerplate, and after changing the export to be 
`module.exports = mongoose.model('RefreshToken', refreshTokenSchema);` instead of 
```
const RefreshToken = mongoose.model('RefreshToken', refreshTokenSchema);
module.exports = RefreshToken;
```

it broke (naturally) - I was thinking of we could improve this a bit by moving the new declaration in the controller?

**Comment by danielfsousa** [comment]
Hey George, I will close this old issue because we will probably switch to Postgres on the next version of the boilerplate.

We can talk about the current problems of the boilerplate and check the progress on https://github.com/danielfsousa/express-rest-boilerplate/issues/334
