### ISSUE TITLE
dependency cycle not best practice

### ISSUE THREAD

**Issue by AidenFaulconer** [danielfsousa/express-rest-boilerplate#270]
In this [file  ](https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/master/src/config/mongoose.js) we can see we require logger ('./../config/logger') which is a workaround from getting a dependency cycle warning, since logger is required in index.js as well (the entry point). Thus forming a dependency cycle. 

Is this best practice? Would this cause an incomplete import from happening if this boilerplate was expanded upon in some instances?

**Comment by danielfsousa** [comment]
We should avoid dependency cycles, there is an eslint rule to prevent this: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md

This issue will be fixed on version 2 https://github.com/danielfsousa/express-rest-boilerplate/issues/334
