### ISSUE TITLE
MongoDB connection error

### ISSUE THREAD

**Issue by Nik720** [danielfsousa/express-rest-boilerplate#292]
Hello folks 

I have tried to set up this as per guild but every time I am getting 

`error: MongoDB connection error: MongooseServerSelectionError: getaddrinfo ENOTFOUND mongodb`

Even I tested with another project to check that Mongodb is working fine or not and it is working fine for another project.

this is the configuration I have 
MongoDB version: 4.2.1
Mongoose: 5.6.7
node: 12.16.1

this is the mongoose connect method

``
exports.connect = () => {
  mongoose
    .connect(mongo.uri, {
      useCreateIndex: true,
      keepAlive: 1,
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useFindAndModify: false,
    })
    .then(() => console.log('mongoDB connected...'));
  return mongoose.connection;
};
``

please help me what is the wrong I am doing.

**Comment by danielfsousa** [comment]
Did you forget to create a .env file? It seems like you are trying to connect to `mongodb`, which is not a valid URI
