### ISSUE TITLE
Wait for mongo connection

### ISSUE THREAD

**Issue by fzaffarana** [danielfsousa/express-rest-boilerplate#304]
I realized that the mongoose connect is an async function. 

Because that, it's possible that the server start without a established mongo connection. (I could generate errors).

I think in something like that:

```
exports.connect = async () => {
  await mongoose
    .connect(mongo.uri, {
      useCreateIndex: true,
      keepAlive: 1,
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useFindAndModify: false,
    })
    .then(() => console.log('mongoDB connected...'));
  return mongoose.connection;
};
```
Or just return `mongoose.connect` as a promise without `then`, and await for the resolution of the promise on the other side.

What do you think about that?

**Comment by danielfsousa** [comment]
I think we can just return the value of mongoose.connect, and await it inside a `async` function (that can be called `main` or something like this) in https://github.com/danielfsousa/express-rest-es2017-boilerplate/blob/master/src/index.js#L9

**Comment by danielfsousa** [comment]
This will be fixed on version 2 https://github.com/danielfsousa/express-rest-boilerplate/issues/334
