### ISSUE TITLE
Replace apidoc with OpenAPI spec

### ISSUE THREAD

**Issue by danielfsousa** [danielfsousa/express-rest-boilerplate#355]
- Add OpenAPI specification in yaml
- Render the documentation when NODE_ENV !== production: https://www.npmjs.com/package/swagger-ui-express
- Test the documentation using https://github.com/apiaryio/dredd

Example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

**Comment by mso1985** [comment]
Hi Daniel, what about something like https://github.com/Surnet/swagger-jsdoc/blob/master/docs/GETTING-STARTED.md

**Comment by danielfsousa** [comment]
Hi @mso1985,

I don't like the approach of using JSDoc for swagger, It gets messy fast. I prefer having a separate yaml file.
