### ISSUE TITLE
.load error in config/var.js file

### ISSUE THREAD

**Issue by adeeldev** [danielfsousa/express-rest-boilerplate#495]
**.load error in config file** 
`TypeError: require(...).load is not a function in /src/config/vars.js:4`

Replace .load with .config like this
`require('dotenv-safe').config({
  path: path.join(__dirname, '../../.env'),
  sample: path.join(__dirname, '../../.env.example'),
**});`**

**Comment by metehankurucu** [comment]
You can replace "load" to "config".

**Comment by adeeldev** [comment]
I just created issue so that you can update in current repo.

**Comment by danielfsousa** [comment]
Thank you. FIxed on https://github.com/danielfsousa/express-rest-boilerplate/commit/eb50c0ef713b2d2409d04083a87342b86c675f9f
